import Head from "next/head";
import Image from "next/image";
import { Inter } from "next/font/google";
const inter = Inter({ subsets: ["latin"] });

export default function Home() {
  return (
    <body>
      <Head>
        <title>Animation</title>
        <meta name="description" content="Generated by Omair Akbar" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/PHOTO.png" />
      </Head>
     <main>
      <div className="list">
      <div className="item"><Image src="/1.jpeg" alt="" height={171} width={115}/></div>
      <div className="item"><Image src="/2.jpg" alt="" height={171} width={115}/></div>
      <div className="item"><Image src="/3.jpeg" alt="" height={171} width={115}/></div>
      <div className="item"><Image src="/4.jpg" alt="" height={171} width={115}/></div>
      <div className="item"><Image src="/5.jpeg" alt="" height={171} width={115}/></div>
      <div className="item"><Image src="/6.jpg" alt="" height={171} width={115}/></div>
      <div className="item"><Image src="/7.jpeg" alt="" height={171} width={115}/></div>
      <div className="item"><Image src="/8.jpg" alt="" height={171} width={115}/></div>
      <div className="item"><Image src="/9.jpeg" alt="" height={171} width={115}/></div>
      <div className="item"><Image src="/10.jpeg" alt="" height={171} width={115}/></div>
      </div>
     </main>
    </body>
  );
}
