import Head from "next/head";
import Image from "next/image";
import { useState,useEffect } from "react";
import { MdFullscreen } from "react-icons/md";
import { MdFullscreenExit } from "react-icons/md";


export default function Home() {
  const [fullScreen,setFullScreen] = useState(false)

  const toggleFullScreen = ()=>{
    const element = document.getElementById("body")
   if(!fullScreen){
    element?.requestFullscreen()
    setFullScreen(true)
  }else{
    if(fullScreen){
      document.exitFullscreen()
      setFullScreen(false)
    }
  }
  }

  
  return (
    <body >
      <Head>
        <title>Animation</title>
        <meta name="description" content="Generated by Omair Akbar" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/PHOTO.png" />
      </Head>
     <main id="body">
      <button onClick={toggleFullScreen} className="fullscreen">{fullScreen ? <MdFullscreenExit className="icon"/> :<MdFullscreen className="icon"/>}</button>
      <div className="heading">
        <h1>Animation NextJs</h1>
        </div>
      <div className="list">
      <div className="item"><Image src="/1.jpeg" alt="" height={96} width={64}/></div>
      <div className="item"><Image src="/2.jpg" alt="" height={96} width={64}/></div>
      <div className="item"><Image src="/3.jpeg" alt="" height={96} width={64}/></div>
      <div className="item"><Image src="/4.jpg" alt="" height={96} width={64}/></div>
      <div className="item"><Image src="/5.jpeg" alt="" height={96} width={64}/></div>
      <div className="item"><Image src="/6.jpg" alt="" height={96} width={64}/></div>
      <div className="item"><Image src="/7.jpeg" alt="" height={96} width={64}/></div>
      <div className="item"><Image src="/8.jpg" alt="" height={96} width={64}/></div>
      <div className="item"><Image src="/9.jpeg" alt="" height={96} width={64}/></div>
      <div className="item"><Image src="/6.jpg" alt="" height={96} width={64}/></div>
      <div className="item"><Image src="/7.jpeg" alt="" height={96} width={64}/></div>
      <div className="item"><Image src="/8.jpg" alt="" height={96} width={64}/></div>
      <div className="item"><Image src="/9.jpeg" alt="" height={96} width={64}/></div>
      <div className="item"><Image src="/10.jpeg" alt="" height={96} width={64}/></div>
      </div>
     </main>
    </body>
  );
}
